In [ ]:
##LOCAL PATH: C:\Users\zailylop\MODULE5
#SECTION # 3 - GET STARTED WITH PYTHON FOR DATA SCIENCE 
#1. Libraries or Modules
import math
math.sqrt(25)


In [3]:
math.pi

3.141592653589793

In [4]:
import math as mt
mt.sqrt(25)

5.0

In [5]:
#2. In your notebook import the following modules and experiment with some of 
#the predefined functions within each module; use the the reference in the resources as a guide:
import numpy 
import math 

#3. Now use numpy to establish some random data we can work with as follows:
from numpy import random
import numpy as np

In [7]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
dataOne

array([[0.91461607, 0.56361542, 0.73322257, 0.12446369, 0.45095691],
       [0.4115899 , 0.06376988, 0.77714675, 0.91038326, 0.7797499 ],
       [0.69739459, 0.01219963, 0.7009671 , 0.79854397, 0.61183696],
       [0.208662  , 0.82209092, 0.77704633, 0.25196805, 0.63689676],
       [0.24533317, 0.27141107, 0.98605992, 0.43224101, 0.5686348 ]])

In [8]:
#4. Now we use a the mean function from within numpy to obtain the mean of the entire array of numbers as follows:
np.mean(dataOne)

0.5500320264904015

In [9]:
#5. Now it is your turn! Use three predefined functions with math and stats to obtain information about the data stored 
#in the numpy array; note any issues you encounter along the way as comments in your notebook. 
#These will serve you well later as lesson learned that you have documented and can reference.

#Zaily's notes: https://docs.python.org/3/library/math.html 

math.factorial(10) #Return x factorial as an integer. Raises ValueError if x is not integral or is negative.

3628800

In [14]:
x=10000
math.isfinite(x) #Return True if x is neither an infinity nor a NaN, and False otherwise.

(0.0, 10.0)

In [13]:
n=10 
math.modf(n) #Return the fractional and integer parts of x. Both results carry the sign of x and are floats.

(0.0, 10.0)

In [15]:
np.array([1, 2, 3])


array([1, 2, 3])

In [17]:
np.array(np.mat('1 2; 3 4'), subok=True)


matrix([[1, 2],
        [3, 4]])

In [18]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3])

In [31]:
##FUNCTIONS 

print('I Love data Science')


I Love data Science


In [32]:
##VARIABLES

z = 25
variableName1 = 'I Love data Science'

print(variableName1)
print(z)


I Love data Science
25


In [35]:
#DATATYPES 
z = 25
type (z)

int

In [36]:
y = 25.0
type (y)

float

In [37]:
varOne = 25
varTwo = 25.0

varThree = varOne + varTwo
print(varThree)

50.0


In [51]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

##Zaily's notes: error because needs to convert the int variables to string

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [52]:
type (varOne)

int

In [49]:
type (varTwo)

str

In [53]:

varThree = str(varOne) + varTwo
print (varThree)

#3. What happened? Did it print out as expected? If not, see if you can research why or why not and find the solution. 
#Be sure to bookmark where you find the answer because you'll likely be returning for other answers!


25Hello


In [54]:
##Lists and Dictionaries
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [56]:
#DICTIONARIES 

tel = {'jack': 4098, 'sape': 4139}
tel['jack']

4098

In [81]:
#1. Now it is your turn! Try the following in your own notebook:
#Define a variable that represents a dictionary with 5 INT elements
#Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. 
#Lastly, print out you results separately.

var_z = {'val1': -1, 'val2': 22, 'val3': 25, 'val4': 100, 'val5': 2222}
var_z


{'val1': -1, 'val2': 22, 'val3': 25, 'val4': 100, 'val5': 2222}

In [63]:
mt.sqrt(var_z['val5'])

47.138094997570704

In [67]:
#100+22
mt.fsum([var_z['val4'], var_z['val2']])

122.0

In [73]:
math.isinf(var_z['val2']) #Return True if x is a positive or negative infinity, and False otherwise.

False

In [82]:
from math import exp, expm1

exp (var_z['val3']) #Calculate the product of all the elements in the input iterable. The default start value for the product is 1.

72004899337.38588